export interface IHistori {
  data: ITtnInfo[] | [];
  errorCodes: Array<unknown> | [];
  errors: Array<unknown> | [];
  info: Array<unknown> | [];
  infoCodes: Array<unknown> | [];
  messageCodes: Array<unknown> | [];
  success: boolean;
  warningCodes: Array<unknown> | [];
  warnings: Array<unknown> | [];
}

export interface ITtnInfo {
  ActualDeliveryDate: string;
  AdditionalInformationEW: string;
  AdjustedDate: string;
  AfterpaymentOnGoodsCost: number;
  AmountPaid: string;
  AmountToPay: string;
  AnnouncedPrice: number;
  AviaDelivery: number;
  BarcodeRedBox: string;
  CalculatedWeight: string;
  CardMaskedNumber: string;
  CargoDescriptionString: string;
  CargoReturnRefusal: boolean;
  CargoType: string;
  CategoryOfWarehouse: string;
  CheckWeight: number;
  CheckWeightMethod: string;
  CityRecipient: string;
  CitySender: string;
  ClientBarcode: string;
  CounterpartyRecipientDescription: string;
  CounterpartySenderDescription: '';
  CounterpartySenderType: string;
  CounterpartyType: string;
  CreatedOnTheBasis: string;
  DateCreated: string;
  DateFirstDayStorage: string;
  DateMoving: string;
  DatePayedKeeping: string;
  DateScan: string;
  DaysStorageCargo: string;
  DeliveryTimeframe: string;
  DocumentCost: string;
  DocumentWeight: number;
  ExpressWaybillAmountToPay: number;
  ExpressWaybillPaymentStatus: string;
  FactualWeight: string;
  FreeShipping: string;
  InternationalDeliveryType: string;
  InternetDocumentDescription: string;
  LastAmountReceivedCommissionGM: number;
  LastAmountTransferGM: string;
  LastCreatedOnTheBasisDateTime: string;
  LastCreatedOnTheBasisDocumentType: string;
  LastCreatedOnTheBasisNumber: string;
  LastCreatedOnTheBasisPayerType: string;
  LastTransactionDateTimeGM: string;
  LastTransactionStatusGM: string;
  LoyaltyCardRecipient: string;
  LoyaltyCardSender: string;
  MarketplacePartnerToken: string;
  Number: string;
  OwnerDocumentNumber: string;
  OwnerDocumentType: string;
  Packaging: Array<unknown> | [];
  PartialReturnGoods: Array<unknown> | [];
  PayerType: string;
  PaymentMethod: string;
  PaymentStatus: string;
  PaymentStatusDate: string;
  PhoneRecipient: string;
  PhoneSender: string;
  PossibilityChangeCash2Card: boolean;
  PossibilityChangeDeliveryIntervals: boolean;
  PossibilityChangeEW: boolean;
  PossibilityCreateRedirecting: boolean;
  PossibilityCreateRefusal: boolean;
  PossibilityCreateReturn: boolean;
  PossibilityTrusteeRecipient: boolean;
  PostomatV3CellReservationNumber: boolean;
  RecipientAddress: string;
  RecipientDateTime: string;
  RecipientFullName: string;
  RecipientFullNameEW: string;
  RecipientWarehouseTypeRef: string;
  Redelivery: number;
  RedeliveryNum: string;
  RedeliveryPayer: string;
  RedeliveryPaymentCardDescription: string;
  RedeliveryPaymentCardRef: string;
  RedeliveryServiceCost: string;
  RedeliverySum: number;
  RefCityRecipient: string;
  RefCitySender: string;
  RefEW: string;
  RefSettlementRecipient: string;
  RefSettlementSender: string;
  ScheduledDeliveryDate: string;
  SeatsAmount: string;
  SecurePayment: false;
  SenderAddress: string;
  SenderFullNameEW: string;
  ServiceType: string;
  Status: string;
  StatusCode: string;
  StorageAmount: string;
  StoragePrice: string;
  SumBeforeCheckWeight: number;
  TrackingUpdateDate: string;
  TrusteeRecipientPhone: string;
  UndeliveryReasons: string;
  UndeliveryReasonsDate: string;
  UndeliveryReasonsSubtypeDescription: string;
  VolumeWeight: string;
  WarehouseRecipient: string;
  WarehouseRecipientAddress: string;
  WarehouseRecipientInternetAddressRef: string;
  WarehouseRecipientNumber: number;
  WarehouseRecipientRef: string;
  WarehouseSender: string;
  WarehouseSenderAddress: string;
  WarehouseSenderInternetAddressRef: string;
  errorCodes: Array<unknown> | [];
  errors: Array<unknown> | [];
  info: Array<unknown> | [];
  infoCodes: Array<unknown> | [];
  messageCodes: Array<unknown> | [];
  success: boolean;
  warningCodes: Array<unknown> | [];
  warnings: Array<unknown> | [];
}
